### ISSUE TITLE
Replace use of custom enum with built-in

### ISSUE THREAD

**Issue by rmarrowstone** [amazon-ion/ion-hash-python#32]
ion-hash-python uses the custom Enum implementation from ion-python. This was done to support enums in python versions prior to 3.4. Now that ion-python only support 3.6 (or higher?) we have dropped usage of it in ion-python but it is still used here.

**Comment by damonmaria** [comment]
This is currently breaking things for me.

This package tries to:
```
from amazon.ion.util import Enum
```

But the current version of the `amazon.ion` package (0.10.0) does not contain `Enum`. But looking in the source it looks like that package as added `Enum` back in (see https://github.com/amazon-ion/ion-python/pull/246) but this hasn't been released yet. 😞

**Comment by rmarrowstone** [comment]
While we do need to release an updated version of ion-python, I have a fix pending to remove the use of the deprecated custom Enum type. Need to get build building on GH first....
