### ISSUE TITLE
Broken with latest amazon.ion

### ISSUE THREAD

**Issue by schlarpc** [amazon-ion/ion-hash-python#36]
https://github.com/amazon-ion/ion-python/commit/7a201c050c1b2a8ea3598d55731692a95321a37c removed `amazon.ion.simple_types._IonNature` which is imported by `ionhash` in `__init__.py`, rendering this module unusable.

**Comment by cheqianh** [comment]
We dropped the Ion Nature for the performance improvement, 

As a short term solution, Did you get a chance to run `pip install -r requirements.txt` to install a recommended version of ion-python? You could find more details in [the develop section](https://github.com/amazon-ion/ion-hash-python?tab=readme-ov-file#development)


I opened an issue to track the long-term solution - https://github.com/amazon-ion/ion-hash-python/issues/37

**Comment by schlarpc** [comment]
Yeah, old versions work fine as a short term solution.
